### ISSUE TITLE
Scatter plot for O2 concentration

### ISSUE THREAD

**Issue by prabhasyadav** [veda1234/CAST-at-IIT#8]
The O2 concentration in the scatter plot (for all fits) - is reading the wrong  values and plotting.
It seems that some form of number is taken as O2 conc., 

My 02 conc. input for four sites are:  2.1, 2.4, 7.68 and 20
In the plot I get the  02 conc. as 25, 26, 27 and 28. 

It seems that some number range is read for O2 conc. 
This happens for all O2 conc. and for all fits. 
The plots and fits are OK for Aq. thickness and Contaminant conc.

 
![Screenshot 2020-05-03 at 14 50 27](https://user-images.githubusercontent.com/19502509/80915270-78656600-8d51-11ea-8bf0-26d533a7aa9a.png)

**Comment by veda1234** [comment]
You can download the latest version of the code, I have fixed the issue.
